### ISSUE TITLE
Dark patches all over

### ISSUE THREAD

**Issue by stan-potapov** [BannerBomb/BetterDiscordThemes#1]
![image](https://user-images.githubusercontent.com/22627776/65358680-33c4fa00-dbc8-11e9-8929-a7e7ba64f343.png)

**Comment by BannerBomb** [comment]
it was related to a discord update. Just to make sure. Make sure you are using the newest theme file. [here](https://github.com/BannerBomb/BetterDiscordThemes/blob/master/themes/ClassicDiscord.theme.css). But if you would like to have the original discord icons you can use the plugin version of it [here]()(https://github.com/BannerBomb/BetterDiscordThemes/blob/master/plugins/ClassicDiscord.plugin.js)
